name: Compress Atmosphere Folder

on:
  workflow_dispatch:  # This allows manual triggering of the action


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Install zip tool
    - name: Install zip
      run: sudo apt-get install zip

    # Step 3: Remove existing NuCheat1.zip (if it exists)
    - name: Remove existing zip file
      run: |
        if [ -f NuCheat1.zip ]; then
          git rm NuCheat1.zip
        fi

    # Step 4: Compress the 'atmosphere' folder into NuCheat1.zip
    - name: Compress folder
      run: zip -r NuCheat1.zip atmosphere/

    # Step 5: Commit and push the zipped file to the main branch using GitHub Token
    - name: Push zipped file to repository
      run: |
        git config --global user.email "nu.guitar@hotmail.com"
        git config --global user.name "nuguitar"
        git add NuCheat1.zip
        git commit -m "Replace NuCheat1.zip in the repository"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}